import React from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, TrendingUp, Target, Award, MessageSquare, Code, ArrowRight, CheckCircle, Zap, Shield } from 'lucide-react';

const Landing = () => {
  return (
    <div className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-primary-50 to-primary-100 py-20 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h1 className="text-5xl font-bold text-gray-800 mb-6">
              Master Your Interview with AI
            </h1>
            <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
              Practice technical interviews with real-time AI feedback. Get personalized insights, 
              improve your skills, and land your dream job.
            </p>
            <div className="flex gap-4 justify-center">
              <Link
                to="/register"
                className="bg-primary-600 text-white px-8 py-4 rounded-lg font-semibold hover:bg-primary-700 transition flex items-center gap-2"
              >
                Get Started Free
                <ArrowRight size={20} />
              </Link>
              <Link
                to="/login"
                className="bg-white text-primary-600 px-8 py-4 rounded-lg font-semibold hover:bg-gray-50 transition border-2 border-primary-600"
              >
                Sign In
              </Link>
            </div>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            <div className="text-center">
              <div className="text-4xl font-bold text-primary-600 mb-2">10K+</div>
              <div className="text-gray-600">Interviews Practiced</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-primary-600 mb-2">95%</div>
              <div className="text-gray-600">Success Rate</div>
            </div>
            <div className="text-center">
              <div className="text-4xl font-bold text-primary-600 mb-2">50+</div>
              <div className="text-gray-600">Tech Roles Covered</div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4 bg-white">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-800 text-center mb-12">
            Everything You Need to Succeed
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <FeatureCard
              icon={<BookOpen className="text-primary-600" size={32} />}
              title="AI-Powered Questions"
              description="Dynamic questions generated by AI tailored to your target role and experience level"
            />
            <FeatureCard
              icon={<TrendingUp className="text-green-600" size={32} />}
              title="Real-time Feedback"
              description="Get instant AI feedback on your answers with detailed analysis and improvement tips"
            />
            <FeatureCard
              icon={<Target className="text-purple-600" size={32} />}
              title="Multiple Interview Modes"
              description="Practice with text answers, MCQs, coding challenges, and HR interviews"
            />
            <FeatureCard
              icon={<Award className="text-yellow-600" size={32} />}
              title="Performance Analytics"
              description="Track your progress with detailed analytics and identify areas for improvement"
            />
            <FeatureCard
              icon={<MessageSquare className="text-orange-600" size={32} />}
              title="Resume Analysis"
              description="AI-powered resume analyzer to optimize your CV for ATS and recruiters"
            />
            <FeatureCard
              icon={<Code className="text-blue-600" size={32} />}
              title="Coding Practice"
              description="Practice coding problems with multiple languages and difficulty levels"
            />
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 px-4 bg-gray-50">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-800 text-center mb-12">
            How It Works
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <StepCard
              number="1"
              title="Create Account"
              description="Sign up for free and select your target role and experience level"
            />
            <StepCard
              number="2"
              title="Practice Interviews"
              description="Choose from various interview modes and practice with AI-generated questions"
            />
            <StepCard
              number="3"
              title="Get Feedback"
              description="Receive detailed AI feedback and track your progress over time"
            />
          </div>
        </div>
      </section>

      {/* Roles Section */}
      <section className="py-20 px-4 bg-white">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-800 text-center mb-12">
            Supported Roles
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
            {[
              'Frontend Developer',
              'Backend Developer',
              'Full Stack Developer',
              'Java Developer',
              'Cyber Security Analyst',
              'Data Analyst'
            ].map((role) => (
              <div
                key={role}
                className="bg-gray-50 rounded-lg p-4 text-center hover:bg-primary-50 transition cursor-pointer"
              >
                <div className="font-medium text-gray-800 text-sm">{role}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 px-4 bg-gray-50">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-800 text-center mb-12">
            What Our Users Say
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <TestimonialCard
              name="Sarah Chen"
              role="Software Engineer"
              company="Google"
              quote="The AI feedback helped me identify my weak areas. I landed my dream job at Google after 3 weeks of practice!"
            />
            <TestimonialCard
              name="Michael Rodriguez"
              role="Full Stack Developer"
              company="Meta"
              quote="Best interview prep tool I've used. The coding challenges and real-time feedback are incredibly helpful."
            />
            <TestimonialCard
              name="Emily Watson"
              role="Frontend Developer"
              company="Amazon"
              quote="The resume analyzer alone is worth it. It helped me optimize my CV and I got 3x more interview calls."
            />
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 bg-primary-600">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl font-bold text-white mb-6">
            Ready to Ace Your Next Interview?
          </h2>
          <p className="text-xl text-primary-100 mb-8">
            Join thousands of developers who have landed their dream jobs with AI Interview Prep
          </p>
          <Link
            to="/register"
            className="bg-white text-primary-600 px-8 py-4 rounded-lg font-semibold hover:bg-gray-100 transition inline-flex items-center gap-2"
          >
            Start Practicing Now
            <ArrowRight size={20} />
          </Link>
        </div>
      </section>

      {/* Features List */}
      <section className="py-20 px-4 bg-white">
        <div className="max-w-7xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-800 text-center mb-12">
            Why Choose Us?
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            <FeatureListItem
              icon={<CheckCircle className="text-green-600" size={20} />}
              text="Unlimited practice sessions"
            />
            <FeatureListItem
              icon={<CheckCircle className="text-green-600" size={20} />}
              text="AI-powered question generation"
            />
            <FeatureListItem
              icon={<CheckCircle className="text-green-600" size={20} />}
              text="Real-time performance feedback"
            />
            <FeatureListItem
              icon={<CheckCircle className="text-green-600" size={20} />}
              text="Multiple interview formats"
            />
            <FeatureListItem
              icon={<CheckCircle className="text-green-600" size={20} />}
              text="Detailed performance analytics"
            />
            <FeatureListItem
              icon={<CheckCircle className="text-green-600" size={20} />}
              text="Resume optimization tools"
            />
            <FeatureListItem
              icon={<Zap className="text-yellow-600" size={20} />}
              text="Fast and responsive platform"
            />
            <FeatureListItem
              icon={<Shield className="text-blue-600" size={20} />}
              text="Secure and private"
            />
          </div>
        </div>
      </section>
    </div>
  );
};

const FeatureCard = ({ icon, title, description }) => (
  <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100 hover:shadow-md transition">
    <div className="mb-4">{icon}</div>
    <h3 className="text-xl font-semibold text-gray-800 mb-2">{title}</h3>
    <p className="text-gray-600">{description}</p>
  </div>
);

const StepCard = ({ number, title, description }) => (
  <div className="text-center">
    <div className="w-16 h-16 bg-primary-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">
      {number}
    </div>
    <h3 className="text-xl font-semibold text-gray-800 mb-2">{title}</h3>
    <p className="text-gray-600">{description}</p>
  </div>
);

const TestimonialCard = ({ name, role, company, quote }) => (
  <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
    <p className="text-gray-700 mb-4 italic">"{quote}"</p>
    <div className="flex items-center gap-3">
      <div className="w-12 h-12 bg-primary-100 rounded-full flex items-center justify-center">
        <span className="text-primary-600 font-semibold">{name.charAt(0)}</span>
      </div>
      <div>
        <div className="font-semibold text-gray-800">{name}</div>
        <div className="text-sm text-gray-600">{role} at {company}</div>
      </div>
    </div>
  </div>
);

const FeatureListItem = ({ icon, text }) => (
  <div className="flex items-center gap-3">
    {icon}
    <span className="text-gray-700">{text}</span>
  </div>
);

export default Landing;
